# Generated by Django 5.2.15 on 2026-06-25 16:28

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import pages.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AirPodsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("earbuds", "Earbuds"), ("case", "Charging case")], max_length=16
                    ),
                ),
                (
                    "image_path",
                    models.CharField(
                        blank=True,
                        help_text=(
                            "Static asset path, for example "
                            "assets/airpods/products/web/airpods-pro-2-earbuds.png."
                        ),
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["kind", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SellerSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("reviewing", "Reviewing"),
                            ("completed", "Completed"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                ("seller_name", models.CharField(max_length=120)),
                ("contact_email", models.EmailField(max_length=254)),
                ("street_address", models.CharField(max_length=255)),
                ("postal_code", models.CharField(max_length=32)),
                ("city", models.CharField(max_length=120)),
                ("country", models.CharField(max_length=120)),
                ("shipping_possible", models.BooleanField(default=False)),
                ("local_handoff_possible", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SellerSubmissionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "part_type",
                    models.CharField(
                        choices=[
                            ("left", "Left AirPod"),
                            ("right", "Right AirPod"),
                            ("case", "Charging case"),
                        ],
                        max_length=12,
                    ),
                ),
                ("model_number", models.CharField(max_length=40)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("damaged", "Damaged"),
                            ("not-sure", "Not sure yet"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "asking_price_eur",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("cleaned_and_ready", models.BooleanField(default=False)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("reviewing", "Reviewing"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                (
                    "airpods_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submission_items",
                        to="pages.airpodsmodel",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pages.sellersubmission",
                    ),
                ),
            ],
            options={
                "ordering": ["submission", "part_type"],
            },
        ),
        migrations.CreateModel(
            name="SellerSubmissionItemPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slot", models.CharField(max_length=40)),
                (
                    "image",
                    models.FileField(upload_to=pages.models.seller_submission_photo_upload_to),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="pages.sellersubmissionitem",
                    ),
                ),
            ],
            options={
                "ordering": ["item", "slot"],
            },
        ),
        migrations.AddConstraint(
            model_name="sellersubmissionitem",
            constraint=models.UniqueConstraint(
                fields=("submission", "part_type"), name="unique_part_type_per_seller_submission"
            ),
        ),
        migrations.AddConstraint(
            model_name="sellersubmissionitemphoto",
            constraint=models.UniqueConstraint(
                fields=("item", "slot"), name="unique_photo_slot_per_seller_submission_item"
            ),
        ),
    ]
